# Generated by Django 6.0.7 on 2026-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='République du Mali', max_length=100, verbose_name='Nom du Pays')),
                ('motto', models.CharField(default='Un Peuple - Un But - Une Foi', max_length=150, verbose_name='Devise du Pays')),
                ('ministry', models.CharField(default="Ministère de l'Éducation Nationale", max_length=150, verbose_name='Ministère tutelle')),
                ('directorate', models.CharField(default="Direction Nationale de l'Enseignement Fondamental", max_length=150, verbose_name='Direction tutelle')),
                ('director_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du Directeur')),
                ('current_academic_year', models.CharField(default='2025-2026', max_length=20, verbose_name='Année scolaire actuelle')),
                ('is_bilingual', models.BooleanField(default=True, verbose_name='Système bilingue (support français-arabe)')),
            ],
            options={
                'verbose_name': 'Paramètre Général',
                'verbose_name_plural': 'Paramètres Généraux',
            },
        ),
    ]
