# Generated by Django 5.1.15 on 2026-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='Sauvegarde automatique')),
                ('last_backup_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sauvegarde')),
            ],
            options={
                'verbose_name': 'Paramètre de sauvegarde',
                'verbose_name_plural': 'Paramètres de sauvegarde',
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du Pays')),
                ('motto', models.CharField(blank=True, max_length=150, null=True, verbose_name='Devise du Pays')),
                ('ministry', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ministère tutelle')),
                ('directorate', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direction tutelle')),
                ('director_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du Directeur')),
                ('current_academic_year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Année scolaire actuelle')),
                ('is_bilingual', models.BooleanField(default=False, verbose_name='Système bilingue (support français-arabe)')),
            ],
            options={
                'verbose_name': 'Paramètre Général',
                'verbose_name_plural': 'Paramètres Généraux',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications SMS')),
            ],
            options={
                'verbose_name': 'Paramètre de notification',
                'verbose_name_plural': 'Paramètres de notification',
            },
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Format recommandé: PNG ou JPG, dimensions carrées', null=True, upload_to='school/', verbose_name="Logo de l'établissement")),
                ('school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'école")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': "Information de l'école",
                'verbose_name_plural': "Informations de l'école",
            },
        ),
    ]
