# Generated by Django 6.0.7 on 2026-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du Pays'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='current_academic_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Année scolaire actuelle'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='directorate',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Direction tutelle'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='is_bilingual',
            field=models.BooleanField(default=False, verbose_name='Système bilingue (support français-arabe)'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='ministry',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ministère tutelle'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='motto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Devise du Pays'),
        ),
    ]
