# Generated by Django 6.0.7 on 2026-08-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0002_alter_generalsetting_country_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Format recommandé: PNG ou JPG, dimensions carrées', null=True, upload_to='school/', verbose_name="Logo de l'établissement")),
                ('school_name', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'école")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': "Information de l'école",
                'verbose_name_plural': "Informations de l'école",
            },
        ),
    ]
