# Generated by Django 6.0.7 on 2026-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0003_schoolsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup', models.BooleanField(default=True, verbose_name='Sauvegarde automatique')),
                ('last_backup_date', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sauvegarde')),
            ],
            options={
                'verbose_name': 'Paramètre de sauvegarde',
                'verbose_name_plural': 'Paramètres de sauvegarde',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications SMS')),
            ],
            options={
                'verbose_name': 'Paramètre de notification',
                'verbose_name_plural': 'Paramètres de notification',
            },
        ),
    ]
