# Generated by Django 6.0.7 on 2026-08-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('student_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Matricule')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Photo')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='students/qrcodes/', verbose_name='QR Code')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='students/barcodes/', verbose_name='Code-barres')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, verbose_name='Sexe')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nationality', models.CharField(default='Mali', max_length=50, verbose_name='Nationalité')),
                ('religion', models.CharField(blank=True, max_length=50, verbose_name='Religion')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Groupe sanguin')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergies')),
                ('medical_notes', models.TextField(blank=True, null=True, verbose_name='Antécédents médicaux')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='Personne à contacter en urgence')),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name="Téléphone d'urgence")),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('documents', models.FileField(blank=True, null=True, upload_to='students/documents/', verbose_name='Documents scannés')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.class', verbose_name='Classe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['-created_at'],
            },
        ),
    ]
