# Generated by Django 5.1.15 on 2026-10-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='parents.parent', verbose_name='Parents / Tuteurs'),
        ),
    ]
