# Generated by Django 5.1.15 on 2026-10-03 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_school_user_school'),
        ('classes', '0003_class_school'),
        ('parents', '0002_parent_school'),
        ('students', '0002_student_parents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accounts.school', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(editable=False, max_length=20, verbose_name='Matricule'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'student_id'), name='unique_student_id_per_school'),
        ),
    ]
