version: '3.8'

services:
  web:
    build: .
    container_name: school_web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python seed_data.py &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-african-school-management-system-super-secret-key-2026
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=school_db
      - DB_USER=school_user
      - DB_PASSWORD=school_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: school_db
    environment:
      - POSTGRES_DB=school_db
      - POSTGRES_USER=school_user
      - POSTGRES_PASSWORD=school_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: school_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ecole.africa
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
