# Generated by Django 5.1.15 on 2026-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la classe')),
                ('level', models.CharField(choices=[('1ère', '1ère année'), ('2ème', '2ème année'), ('3ème', '3ème année'), ('4ème', '4ème année'), ('5ème', '5ème année'), ('6ème', '6ème année'), ('7ème', '7ème année'), ('8ème', '8ème année'), ('9ème', '9ème année'), ('10ème', '10ème Année (Seconde)'), ('11ème', '11ème Année (Première)'), ('12ème', '12ème Année (Terminal)'), ('Seconde', 'Seconde'), ('Première', 'Première'), ('Terminale', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('Doctorat', 'Doctorat')], max_length=20, verbose_name='Niveau')),
                ('section', models.CharField(choices=[('Française', 'Française'), ('Arabe', 'Arabe'), ('Mixte', 'Mixte')], default='Française', max_length=20, verbose_name='Section')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Capacité')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Salle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Classe active')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['level', 'name'],
            },
        ),
    ]
