# Generated by Django 6.0.7 on 2026-08-05 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la classe')),
                ('level', models.CharField(choices=[('1ère', '1ère année'), ('2ème', '2ème année'), ('3ème', '3ème année'), ('4ème', '4ème année'), ('5ème', '5ème année'), ('6ème', '6ème année'), ('7ème', '7ème année'), ('8ème', '8ème année'), ('9ème', '9ème année')], max_length=20, verbose_name='Niveau')),
                ('section', models.CharField(choices=[('Française', 'Française'), ('Arabe', 'Arabe'), ('Mixte', 'Mixte')], default='Française', max_length=20, verbose_name='Section')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='Capacité')),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Salle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Classe active')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_managed', to='teachers.teacher', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['level', 'name'],
            },
        ),
    ]
