# Generated by Django 6.0.7 on 2026-08-15 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.program', verbose_name='Programme / Filière'),
        ),
        migrations.AlterField(
            model_name='class',
            name='level',
            field=models.CharField(choices=[('1ère', '1ère année'), ('2ème', '2ème année'), ('3ème', '3ème année'), ('4ème', '4ème année'), ('5ème', '5ème année'), ('6ème', '6ème année'), ('7ème', '7ème année'), ('8ème', '8ème année'), ('9ème', '9ème année'), ('10ème', '10ème Année (Seconde)'), ('11ème', '11ème Année (Première)'), ('12ème', '12ème Année (Terminal)'), ('Seconde', 'Seconde'), ('Première', 'Première'), ('Terminale', 'Terminale'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('Doctorat', 'Doctorat')], max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la classe'),
        ),
    ]
