# Generated by Django 5.1.15 on 2026-10-03 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('path', models.CharField(max_length=200, verbose_name='Page')),
                ('day', models.DateField(db_index=True, verbose_name='Jour')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Visiteur')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-day', '-created_at'],
                'indexes': [models.Index(fields=['day', 'path'], name='analytics_v_day_3f64b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day', 'path'), name='uniq_visit_user_day_path'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_key', 'day', 'path'), name='uniq_visit_session_day_path')],
            },
        ),
    ]
