# Generated by Django 5.1.15 on 2026-07-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=150, verbose_name='Libellé du frais (ex: Tranche 1 Scolarité)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant requis (FCFA / EUR)')),
                ('due_date', models.DateField(verbose_name="Date limite d'échéance")),
                ('academic_year', models.CharField(default='2025-2026', max_length=20, verbose_name='Année Académique')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='students.classroom', verbose_name='Classe ciblée')),
            ],
            options={
                'verbose_name': 'Structure de Frais',
                'verbose_name_plural': 'Structures de Frais',
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant réglé')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de versement')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces (Caisse)'), ('BANK_TRANSFER', 'Virement BTP / Banque'), ('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave Mobile Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('CHEQUE', 'Chèque bancaire')], default='ORANGE_MONEY', max_length=30, verbose_name='Mode de paiement')),
                ('receipt_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de reçu officiel')),
                ('is_receipt_issued', models.BooleanField(default=True, verbose_name='Reçu officiel validé et émis')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.feestructure', verbose_name='Frais rattaché')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.studentprofile', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Paiement Étudiant',
                'verbose_name_plural': 'Paiements Étudiants',
                'constraints': [models.UniqueConstraint(fields=('receipt_number',), name='unique_receipt_number')],
            },
        ),
    ]
