# Generated by Django 5.1.15 on 2026-10-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tuition_expense_payment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
