# Generated by Django 5.1.15 on 2026-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('application_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de Dossier')),
                ('applicant_first_name', models.CharField(max_length=150, verbose_name='Prénom du candidat')),
                ('applicant_last_name', models.CharField(max_length=150, verbose_name='Nom du candidat')),
                ('applicant_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('applicant_phone', models.CharField(max_length=30, verbose_name='Téléphone de contact')),
                ('status', models.CharField(choices=[('PENDING', "En attente d'examen"), ('INTERVIEW', 'Entretien programmé'), ('APPROVED', 'Admission Approuvée'), ('REJECTED', 'Candidature Refusée')], default='PENDING', max_length=20, verbose_name='Statut du dossier')),
                ('documents', models.FileField(blank=True, null=True, upload_to='admissions/', verbose_name='Dossier scolaire antérieur (PDF)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Notes de la commission d'admission")),
            ],
            options={
                'verbose_name': "Demande d'admission",
                'verbose_name_plural': "Demandes d'admission",
            },
        ),
    ]
