# Generated by Django 5.1.15 on 2026-09-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='requested_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='classes.class', verbose_name='Niveau / Classe visée'),
        ),
        migrations.AddConstraint(
            model_name='admissionapplication',
            constraint=models.UniqueConstraint(fields=('application_number',), name='unique_admission_app_number'),
        ),
    ]
