# Generated by Django 5.1.15 on 2026-09-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur / Direction'), ('COMPTABLE', 'Comptable'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Étudiant'), ('PARENT', "Parent d'élève")], default='STUDENT', max_length=20, verbose_name="Rôle dans l'établissement"),
        ),
    ]
