# Generated by Django 5.1.15 on 2026-10-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name="Nom de l'école")),
                ('code', models.SlugField(blank=True, max_length=30, unique=True, verbose_name='Code')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contact')),
                ('plan', models.CharField(choices=[('GRATUIT', 'Gratuit'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STANDARD', max_length=10, verbose_name='Formule')),
            ],
            options={
                'verbose_name': 'École (plateforme)',
                'verbose_name_plural': 'Écoles (plateforme)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.school', verbose_name='École (rattachement)'),
        ),
    ]
