# Generated by Django 5.1.15 on 2026-10-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la formule')),
                ('code', models.SlugField(blank=True, max_length=30, unique=True, verbose_name='Code')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (FCFA / période)')),
                ('duration_days', models.PositiveIntegerField(default=30, verbose_name='Durée (jours)')),
                ('max_students', models.PositiveIntegerField(blank=True, null=True, verbose_name="Plafond d'élèves (vide = illimité)")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('features', models.TextField(blank=True, help_text='Une fonctionnalité par ligne.', null=True, verbose_name='Fonctionnalités incluses')),
                ('is_active', models.BooleanField(default=True, verbose_name="Proposée à l'inscription")),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['price'],
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_until',
            field=models.DateField(blank=True, null=True, verbose_name="Abonnement valable jusqu'au"),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('Bamako', 'District de Bamako'), ('Kayes', 'Kayes'), ('Koulikoro', 'Koulikoro'), ('Sikasso', 'Sikasso'), ('Ségou', 'Ségou'), ('Mopti', 'Mopti'), ('Gao', 'Gao'), ('Tombouctou', 'Tombouctou'), ('Kidal', 'Kidal'), ('Ménaka', 'Ménaka'), ('Taoudénit', 'Taoudénit'), ('Hors Mali', 'Hors Mali')], max_length=50, verbose_name='Région'),
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('platform_name', models.CharField(default="Gestion d'École", max_length=150, verbose_name='Nom de la plateforme')),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du support')),
                ('public_registration_enabled', models.BooleanField(default=True, verbose_name="Autoriser l'inscription publique des écoles")),
                ('default_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='accounts.subscriptionplan', verbose_name='Abonnement attribué par défaut')),
            ],
            options={
                'verbose_name': 'Paramètre de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='accounts.subscriptionplan', verbose_name='Abonnement'),
        ),
    ]
