# Generated by Django 5.1.15 on 2026-09-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'examen")),
                ('exam_type', models.CharField(choices=[('CC', 'Contrôle Continu'), ('PARTIAL', 'Examen Partiel'), ('FINAL', 'Examen Final')], default='CC', max_length=20, verbose_name="Type d'examen")),
                ('date', models.DateTimeField(verbose_name="Date et heure de l'épreuve")),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Durée (en minutes)')),
                ('total_points', models.FloatField(default=20.0, verbose_name='Note maximale (sur 20 par défaut)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course', verbose_name='Cours concerné')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('question_type', models.CharField(choices=[('MCQ', 'Question à Choix Multiple (QCM)'), ('TEXT', 'Réponse Rédactionnelle / Texte'), ('FILE', 'Soumission de fichier / Schéma')], default='TEXT', max_length=10, verbose_name='Type de question')),
                ('text', models.TextField(verbose_name='Énoncé de la question')),
                ('points', models.FloatField(default=2.0, verbose_name='Points de la question')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Options QCM (séparées par une virgule si QCM)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Examen')),
            ],
            options={
                'verbose_name': "Question d'examen",
                'verbose_name_plural': "Questions d'examen",
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('score', models.FloatField(verbose_name='Note obtenue')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Appréciation / Remarques')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='Examen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': "Résultat d'examen",
                'verbose_name_plural': "Résultats d'examens",
                'constraints': [models.UniqueConstraint(fields=('exam', 'student'), name='unique_student_exam_result')],
            },
        ),
    ]
