# Generated by Django 6.0.7 on 2026-08-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur Hex (ex: #3B82F6)')),
            ],
            options={
                'verbose_name': "Catégorie d'événement",
                'verbose_name_plural': "Catégories d'événements",
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Toute la journée')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('programs', models.ManyToManyField(blank=True, related_name='events', to='courses.program', verbose_name='Programmes / Classes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='school_calendar.eventcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Événement académique',
                'verbose_name_plural': 'Événements académiques',
                'ordering': ['start_date'],
            },
        ),
    ]
