# Generated by Django 6.0.7 on 2026-08-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(max_length=100, verbose_name='Spécialité / Matière'),
        ),
    ]
