# Generated by Django 5.1.15 on 2026-07-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date', models.DateField(verbose_name='Date de la séance')),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('LATE', 'En Retard'), ('EXCUSED', 'Absence Excusée / Justifiée')], default='PRESENT', max_length=15, verbose_name='Statut de présence')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motif / Remarques')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.course', verbose_name='Cours')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.studentprofile', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Enregistrement de Présence',
                'verbose_name_plural': 'Enregistrements de Présence',
            },
        ),
        migrations.CreateModel(
            name='AbsenceJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reason', models.TextField(verbose_name="Motif de l'absence")),
                ('document', models.FileField(blank=True, null=True, upload_to='justifications/', verbose_name='Justificatif Médical / Officiel')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé par la Direction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='students.studentprofile', verbose_name='Étudiant')),
                ('attendance_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justification', to='attendance.attendancerecord', verbose_name='Séance concernée')),
            ],
            options={
                'verbose_name': "Justificatif d'absence",
                'verbose_name_plural': "Justificatifs d'absences",
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'date'), name='unique_student_course_attendance_date'),
        ),
    ]
