# Generated by Django 5.1.15 on 2026-09-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=50, verbose_name='Semestre (ex: Semestre 1)')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20, verbose_name='Année Académique')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='ClassroomRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code Salle')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la salle / Amphi')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bâtiment / Pavillon')),
                ('capacity', models.PositiveIntegerField(default=50, verbose_name="Capacité d'accueil")),
            ],
            options={
                'verbose_name': 'Salle de cours',
                'verbose_name_plural': 'Salles de cours',
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_room_code')],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('day', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')], verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
            ],
            options={
                'verbose_name': 'Créneau Horaire',
                'verbose_name_plural': 'Créneaux Horaires',
                'constraints': [models.UniqueConstraint(fields=('day', 'start_time', 'end_time'), name='unique_timeslot_slot')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='Cours')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trs.classroomroom', verbose_name='Salle')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trs.semester', verbose_name='Semestre')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trs.timeslot', verbose_name='Créneau Horaire')),
            ],
            options={
                'verbose_name': "Planification d'emploi du temps",
                'verbose_name_plural': "Planifications d'emplois du temps",
                'constraints': [models.UniqueConstraint(fields=('room', 'time_slot', 'semester'), name='unique_room_slot_semester')],
            },
        ),
    ]
