# Generated by Django 5.1.15 on 2026-09-26 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('CERTIFICAT', 'Certificats & Attestations'), ('PEDAGOGIQUE', 'Documents Pédagogiques & Classes'), ('RH', 'Documents du Personnel / RH'), ('ADMINISTRATIF', 'Documents Administratifs & Généraux')], max_length=50)),
                ('type_fichier', models.CharField(choices=[('PDF', 'Document PDF'), ('WORD', 'Document Word (.docx)'), ('EXCEL', 'Feuille Excel (.xlsx)')], default='PDF', max_length=10)),
                ('fichier', models.FileField(upload_to='documents/modeles/')),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé de maternité / paternité'), ('SANS_SOLDE', "Autorisation d'absence sans solde"), ('AUTRE', 'Autre')], max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
            },
        ),
    ]
