# Generated by Django 5.1.15 on 2026-09-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du programme')),
                ('name', models.CharField(max_length=250, verbose_name='Nom du programme')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la matière')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code du cours')),
                ('name', models.CharField(max_length=150, verbose_name='Intitulé du cours')),
                ('credits', models.PositiveSmallIntegerField(default=1, verbose_name='Crédits')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classes.class', verbose_name='Classe')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='teachers.teacher', verbose_name='Enseignant')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'unique_together': {('subject', 'school_class')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Cours')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Inscription à un cours',
                'verbose_name_plural': 'Inscriptions aux cours',
                'unique_together': {('course', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient')),
                ('hours_per_week', models.PositiveIntegerField(default=2, verbose_name='Heures/Semaine')),
                ('total_hours', models.PositiveIntegerField(default=30, verbose_name='Volume Horaire Total')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Optionnelle ?')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects', to='courses.program')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to='teachers.teacher', verbose_name='Enseignant titulaire')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_programs', to='courses.subject')),
            ],
            options={
                'verbose_name': 'Matière du programme',
                'verbose_name_plural': 'Matières des programmes',
                'unique_together': {('program', 'subject')},
            },
        ),
    ]
