# Generated by Django 6.0.7 on 2026-08-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0002_alter_teacher_email_alter_teacher_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code du programme')),
                ('name', models.CharField(max_length=250, verbose_name='Nom du programme')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient')),
                ('hours_per_week', models.PositiveIntegerField(default=2, verbose_name='Heures/Semaine')),
                ('total_hours', models.PositiveIntegerField(default=30, verbose_name='Volume Horaire Total')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Optionnelle ?')),
            ],
            options={
                'verbose_name': 'Matière du programme',
                'verbose_name_plural': 'Matières des programmes',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_code',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_course_enrollment',
        ),
        migrations.AddField(
            model_name='programsubject',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects', to='courses.program'),
        ),
        migrations.AddField(
            model_name='programsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subjects', to='teachers.teacher', verbose_name='Enseignant titulaire'),
        ),
        migrations.AddField(
            model_name='programsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_programs', to='courses.subject'),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='programsubject',
            unique_together={('program', 'subject')},
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
