# Generated by Django 5.1.15 on 2026-07-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du devoir')),
                ('description', models.TextField(verbose_name='Consignes / Description')),
                ('due_date', models.DateTimeField(verbose_name='Date et heure limite')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Pièce jointe du sujet')),
                ('max_score', models.FloatField(default=20.0, verbose_name='Note maximale')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='Cours concerné')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('submission_text', models.TextField(blank=True, null=True, verbose_name='Réponse en ligne')),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Fichier du devoir rendu')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Note attribuée')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name="Commentaires / Feedback de l'enseignant")),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Devoir')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.studentprofile', verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Soumission de devoir',
                'verbose_name_plural': 'Soumissions de devoirs',
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student'), name='unique_student_assignment_submission')],
            },
        ),
    ]
