# Generated by Django 5.1.15 on 2026-09-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du devoir')),
                ('description', models.TextField(verbose_name='Consignes / Description')),
                ('due_date', models.DateTimeField(verbose_name='Date et heure limite')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Pièce jointe du sujet')),
                ('max_score', models.FloatField(default=20.0, verbose_name='Note maximale')),
            ],
            options={
                'verbose_name': 'Devoir',
                'verbose_name_plural': 'Devoirs',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('submission_text', models.TextField(blank=True, null=True, verbose_name='Réponse en ligne')),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Fichier du devoir rendu')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Note attribuée')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name="Commentaires / Feedback de l'enseignant")),
            ],
            options={
                'verbose_name': 'Soumission de devoir',
                'verbose_name_plural': 'Soumissions de devoirs',
            },
        ),
    ]
